# Generated by Django 2.1.5 on 2019-02-12 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20190212_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'MySubscriber', 'verbose_name_plural': 'a lot of subscriber'},
        ),
    ]
