# Generated by Django 2.1.5 on 2019-02-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190213_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='total_amount',
            new_name='total_price',
        ),
    ]
